### ISSUE TITLE
Add Search Box

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/next-geek#3]
@idhyt Hi, I forked your repository several days ago.

I am customizing my own blog based on your theme.

I like your search box in your blog. Just like the picture below.
![image](https://cloud.githubusercontent.com/assets/12933851/22786782/e3cabb72-ef14-11e6-837c-1a144b37062d.png)

Could you tell me how to do that since I don't know too much about javascript or something.

**Comment by idhyt** [comment]
@Gabirel 
sorry, I don't know too much about javascript too, but I can tell you a way to change it.
right click the search box and select `Inspect`, you can locate the code of it.

**Comment by Gabirel** [comment]
@idhyt thank for your help

**Comment by Gabirel** [comment]
Merged in #19
