### ISSUE TITLE
Surprise ball is covered by long titles

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/next-geek#44]
### Expected behavior
![image](https://cloud.githubusercontent.com/assets/12933851/26569593/1aae5142-453e-11e7-8972-afe7ffa6459a.png)

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/12933851/26569574/024a4174-453e-11e7-8c19-f17314daa04d.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release  ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces
  -  Mala    ✔

**Comment by youzhiye** [comment]
36 line,top 50 => 15
