### ISSUE TITLE
The position of the b2t button is wrong

### ISSUE THREAD

**Issue by HanielF** [Gabirel/next-geek#55]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The position of b2t button,the button of back to top, should below the sidebar button. 

### Actual behavior 
It's on the center of sidebar.

### Steps to reproduce the behavior 
1. vim next-geek/_config.yml 
2. /b2t
3.b2t: true

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[x] Mala
```
The b2t option do let you back to top of  the window ,rather than make the button on the top of sidebar.
Let it false, then the button of back to top will disappear.

### Other Information <!-- (Like Browser, System, Screenshots) --
![b2t](https://user-images.githubusercontent.com/24732516/29673609-5e73db12-88b5-11e7-9bb3-45ac8d5a1371.png)

**Comment by Gabirel** [comment]
The upstream has the same feature. So, you can't call it a bug. If you want this feature and you think that color is ugly, you can tell me to improve it. I won't change this feature unless you actually want that.

**Comment by HanielF** [comment]
But how can i move it to bottom of sidebar? 
Just like the screenshot:
![image](https://user-images.githubusercontent.com/24732516/29718043-fa63ed62-89e3-11e7-8077-f79cf57b4ca1.png)
Really exists any configuration in file _config.yml that can move it to the bottom?

**Comment by Gabirel** [comment]
Reset all of your config. That should work for you.
