### ISSUE TITLE
Position of the bottom bar in Tags, Categories, About,and Archives pages are wrong.

### ISSUE THREAD

**Issue by HanielF** [Gabirel/next-geek#56]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The copyright ,author, powered by,and theme,should be the bottom of the website.

### Actual behavior 
It is on the middle of website now.

### Steps to reproduce the behavior 
1. I did nothing to the configuration which is related to it.
2.What's more , i don't know how to control it in the _config.yml file

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[x] Mala
```

### Other Information <!-- (Like Browser, System, Screenshots) --
Browser: chrome
System: Fedora 25
Screenshot:
![blog](https://user-images.githubusercontent.com/24732516/29705418-8b9d51ca-8943-11e7-891c-04148fdba874.png)

**Comment by HanielF** [comment]
Archives:



Categories:
![Uploading image.png…]()

**Comment by Gabirel** [comment]
I find it that upstream also has the same "issue". I don't know whether do it without intention.

**Comment by HanielF** [comment]
The problem still exists in about page.
<https://catchdream.me/about/>

**Comment by Gabirel** [comment]
Please update and try it again.

**Comment by Gabirel** [comment]
It should do the trick, I guess. You should try the latest code

**Comment by HanielF** [comment]
It doesn't work …
I have updated my repo before.

**Comment by Gabirel** [comment]
You must add the following below:
`type: "about"`

The full `about` page:
```yml
---
title: about
date: 2017-08-27 17:20:45
type: "about"
comments: false
---
```

**Comment by HanielF** [comment]
The position is right now. Thanks~
